#!/bin/bash
# MySQL backup script
# Last update: 19.02.2013


MHOST=localhost
MUSER=
MPASS=
BACKUPDIR="."

########################################################################

MYSQL="$(which mysql)"
MYSQLDUMP="$(which mysqldump)"
GZIP="$(which gzip)"

DBPREFIX="$(hostname -s).mysqldb"

echo "Run MySQL backup"
DBS="$($MYSQL -u $MUSER -h $MHOST -p$MPASS -Bse 'show databases')"
for db in $DBS
do
  FILE=${BACKUPDIR}/${DBPREFIX}.${db}.gz
  touch $FILE 

  $MYSQLDUMP --no-tablespaces --skip-lock-tables -u $MUSER -h $MHOST -p$MPASS $db | $GZIP -9 > $FILE
done
